### ISSUE TITLE
Add script

### ISSUE THREAD

**Issue by bimoso** [IShade4ReaI/NetflixCE#7]
For a game that I think is played by many, I'm talking about blox fruits, maybe with _G.bloxFruits() this script is executed "_```loadstring(game:HttpGet('https://link.trwxz.com/LS-Wolf-Hub'))()```_" and with _G.findFruits this 
"_
```Fruits = {
"Rocket Fruit",
"Spin Fruit",
"Chop Fruit",
"Spring Fruit",
"Bomb Fruit",
"Smoke Fruit",
"Spike Fruit",
"Flame Fruit",
"Bird: Falcon Fruit",
"Ice Fruit",
"Sand Fruit",
"Dark Fruit",
"Diamond Fruit",
"Light Fruit",
"Rubber Fruit",
"Barrier Fruit",
"Ghost Fruit",
"Magma Fruit",
"Quake Fruit",
"Human: Buddha Fruit",
"Love Fruit",
"Spider Fruit",
"Sound Fruit",
"Bird: Phoenix Fruit",
"Portal Fruit",
"Portal Fruit",
"Pain Fruit",
"Blizzard Fruit",
"Gravity Fruit",
"Mammoth Fruit",
"Dough Fruit",
"Shadow Fruit",
"Venom Fruit",
"Control Fruit",
"Spirit Fruit",
"Dragon Fruit" ,
"Leopard Fruit"
}
Valuable = {"Rocket Fruit","Spin Fruit","Chop Fruit","Spring Fruit","Bomb Fruit","Smoke Fruit","Spike Fruit","Flame Fruit","Bird: Falcon Fruit","Ice Fruit","Sand Fruit","Dark Fruit","Diamond Fruit","Light Fruit","Rubber Fruit","Barrier Fruit","Ghost Fruit","Magma Fruit","Quake Fruit","Human: Buddha Fruit","Love Fruit","Spider Fruit","Sound Fruit","Bird: Phoenix Fruit","Portal Fruit","Portal Fruit","Pain Fruit","Blizzard Fruit","Gravity Fruit","Mammoth Fruit","Dough Fruit","Shadow Fruit","Venom Fruit","Control Fruit","Spirit Fruit","Dragon Fruit" ,"Leopard Fruit"} -- it will stop the script if you got this fruit
Webhook = ""
Store = true
Safeplace = true
Repeat = true
-----------------------------------------------------------------------
loadstring(game:HttpGet"https://gist.githubusercontent.com/NotHubris/4e6fdc88d84c30afa9b28c590f273bbf/raw")()```
_"

**Comment by SoftwarePixel** [comment]
Okay, so you really shouldn't open an issue for a suggestion. Furthermore, you clearly don't understand how this works at all. You literally just pasted an obfuscated script and said "add this pls." This exploit is what we call level 2. It essentially just takes the script and runs it as part of the tool's local script. Roblox does not allow client side to load strings, but that's not even the worst part of this, your loading a heavily obfuscated script, so it wouldn't even be possible to modify it to run as a simple local script. Not to be rude, but you clearly have no idea what your talking about, nor do you understand how exploiting works. That's pretty much the definition of a script kid, please try to learn about what your doing and benefit the community rather than just copy and pasting scripts.
